version: 1.0.{build}
clone_folder: c:\projects\caffe
environment:
  matrix:
    - MSVC_VERSION: 14
      WITH_NINJA: 0
      CMAKE_CONFIG: Release
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 3
      WITH_CUDA: 0

    - MSVC_VERSION: 14
      WITH_NINJA: 0
      CMAKE_CONFIG: Release
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 0

    - MSVC_VERSION: 14
      WITH_NINJA: 0
      CMAKE_CONFIG: Debug
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 0

    - MSVC_VERSION: 14
      WITH_NINJA: 1
      CMAKE_CONFIG: Release
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 0

    - MSVC_VERSION: 14
      WITH_NINJA: 1
      CMAKE_CONFIG: Debug
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 0
      
    - MSVC_VERSION: 14
      WITH_NINJA: 1
      CMAKE_CONFIG: Release
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 1
      
    - MSVC_VERSION: 14
      WITH_NINJA: 1
      CMAKE_CONFIG: Release
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 3
      WITH_CUDA: 1        

    - MSVC_VERSION: 12
      WITH_NINJA: 0
      CMAKE_CONFIG: Release
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 0

    - MSVC_VERSION: 12
      WITH_NINJA: 0
      CMAKE_CONFIG: Debug
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 0

    - MSVC_VERSION: 12
      WITH_NINJA: 1
      CMAKE_CONFIG: Release
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 0

    - MSVC_VERSION: 12
      WITH_NINJA: 1
      CMAKE_CONFIG: Debug
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 0
  
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - cmd: SET VCTargetsPath="C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install -g --production windows-build-tools

build_script:
- cmd: >-
    call scripts\build_win.cmd

artifacts:
  - path: build\install
    name: caffe
    
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
