version: 1.0.{build}
clone_folder: c:\projects\caffe
environment:
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAwQ1GiEcwrP6lkJPh380v/rUPdgx3SqIUzjGEApmfbjgyskts8Cs3vIsIphh2OgjxdLdDRVj3fa47QxUrfG4il5oUgYJAMTXFC0rI9Yii44HHcWPAXNMbDvq8B3sBrEDm3mLFaDtzOJKTn1759tAKPv6GCl+NtebuFcWvfJjSDa0Z+GXfsnND1dQYG46DJEsg3KHFwaEx5AS547eM+QpLhOl7tVoD+UlDHBeUFtOPw1wOjkC9g2DxeWCLcfehUhuJgFtrIpy/2mDsoMZQ5F4Zc3hko2j9xhI5XmtB5aJZUIUL7MMcbWigP4gkrpfqlK59VddbtXjG6HjUGcqmsXLy4w==

  matrix:
    - MSVC_VERSION: 14
      WITH_NINJA: 0
      CMAKE_CONFIG: Release
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 3
      WITH_CUDA: 0

    - MSVC_VERSION: 14
      WITH_NINJA: 0
      CMAKE_CONFIG: Release
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 0

    - MSVC_VERSION: 14
      WITH_NINJA: 0
      CMAKE_CONFIG: Debug
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 0

    - MSVC_VERSION: 14
      WITH_NINJA: 1
      CMAKE_CONFIG: Release
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 0

    - MSVC_VERSION: 14
      WITH_NINJA: 1
      CMAKE_CONFIG: Debug
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 0
      
    - MSVC_VERSION: 14
      WITH_NINJA: 1
      CMAKE_CONFIG: Release
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 1
      
    - MSVC_VERSION: 14
      WITH_NINJA: 1
      CMAKE_CONFIG: Release
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 3
      WITH_CUDA: 1        

    - MSVC_VERSION: 12
      WITH_NINJA: 0
      CMAKE_CONFIG: Release
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 0

    - MSVC_VERSION: 12
      WITH_NINJA: 0
      CMAKE_CONFIG: Debug
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 0

    - MSVC_VERSION: 12
      WITH_NINJA: 1
      CMAKE_CONFIG: Release
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 0

    - MSVC_VERSION: 12
      WITH_NINJA: 1
      CMAKE_CONFIG: Debug
      CMAKE_BUILD_SHARED_LIBS: 0
      PYTHON_VERSION: 2
      WITH_CUDA: 0
  
init:
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install -g --production windows-build-tools

build_script:
- cmd: >-
    call scripts\build_win.cmd

artifacts:
  - path: build\install
    name: caffe
    
on_finish:
  - sh: export APPVEYOR_SSH_BLOCK=true
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
